global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: peergrid-compose
    metrics_path: /metrics
    static_configs:
      - targets:
          - server:3001

  - job_name: peergrid-server-nodes
    metrics_path: /metrics
    static_configs:
      - targets:
          - host.docker.internal:3000
          - host.docker.internal:3001
          - host.docker.internal:3002
        labels:
          cluster: peergrid
