/**
 * simulator/simulatorMetrics.ts
 *
 * Prometheus metrics specific to the editor swarm simulator.
 * Registered on the shared PeerGrid registry so they appear alongside
 * production metrics at GET /metrics.
 */

import { Gauge, Counter } from 'prom-client';
import { register } from '../metrics/metrics';

// ── Simulated editors currently active ──────────────────────────────────────

export const simEditorsGauge = new Gauge({
  name: 'peergrid_sim_editors_active',
  help: 'Number of simulated editors currently running',
  registers: [register],
});

// ── Total edits generated by the simulator ──────────────────────────────────

export const simEditsCounter = new Counter({
  name: 'peergrid_sim_edits_generated_total',
  help: 'Total number of CRDT edits generated by the simulator',
  registers: [register],
});

// ── Connection failures from simulated editors ──────────────────────────────

export const simConnectionFailuresCounter = new Counter({
  name: 'peergrid_sim_connection_failures_total',
  help: 'Total number of WebSocket connection failures from simulated editors',
  registers: [register],
});

// ── Average latency of simulated edits ──────────────────────────────────────

export const simAvgLatencyGauge = new Gauge({
  name: 'peergrid_sim_avg_latency_ms',
  help: 'Average local edit latency in milliseconds (doc mutation + encode + send)',
  registers: [register],
});
